"use strict";
console.log('it compiles correctly');
var number = 38;
console.log(number);
number = 1;
console.log(number);
var age;
age = 29;
console.log(age);
age = 34;
console.log(age);
var names = ['james', 'billy', 'steve'];
console.log(names);
names[0] = 100;
console.log(names);
